@host = http://127.0.0.1:5000/v1/cats

###Get all cats
GET {{host}}/?fields=name&offset=0&limit=2 HTTP/1.1


###Post specific Cat
POST {{host}}/ HTTP/1.1
Content-Type: application/json

{
    "id": 0,
    "name": "Minky"
}

###
PUT {{host}}/ HTTP/1.1
Content-Type: application/json

{
    "id": 1,
    "name": "Bravo"
}


###
DELETE {{host}}/ HTTP/1.1
Content-Type: application/json





###
GET {{host}}/1 HTTP/1.1


